### PR TITLE
Missing options from Prettier Miscellaneous

### PR DESCRIPTION
**Pull request by remimarsal**
Added the following options in the extension configuration :

- bracesSpacing
- breakProperty
- arrowParens
- arrayExpand
- flattenTernaries
- breakBeforeElse
- groupFirstArg
- noSpaceEmptyFn

### CODE REVIEW

**Comment by langdonx** [comment]
@passionkind Any chance this can get pulled in and the extension updated on the marketplace?  Was looking to use `breakBeforeElse`.

**Comment by langdonx** [comment]
@remimarsal Do you not also need to update dependencies in `package.json` to `"prettier-miscellaneous": "^1.4.2"`?

**Comment by remimarsal** [comment]
@langdonx I guess Bastian is bit busy at the moment. I didn't want to wait so I ended up building the extension myself with a version bump on prettier-miscellaneous to 1.4.2.  You can find it [here](https://marketplace.visualstudio.com/items?itemName=remimarsal.prettier-now).

**Comment by langdonx** [comment]
@remimarsal Awesome!  The name is perfect.

I can't get a few of the new options to work (specifying them in settings.json): (`"prettier.bracesSpacing": false, "prettier.breakBeforeElse": true`).  Other new ones, like `prettier.arrowParens` work fine.

Do you want to open up Issues on your fork?

**Pull request closed without merging**
